version: "3"

services:
  hello-docker-react:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hello-docker-react
    entrypoint: sh entrypoint.sh
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
